// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (c) 2026 Cairn maintainers and contributors

//! Android Key Attestation verification per D0033 (Stage 1).
//!
//! [`verify_key_attestation`] cryptographically PROVES that the device
//! signing key lives in secure hardware (TEE / `StrongBox`), is
//! non-exportable, and was generated in-hardware — by verifying the
//! X.509 attestation certificate chain that `KeyMint` emits at
//! key-generation time, rather than trusting the Kotlin
//! `KeyInfo.securityLevel` self-report (D0020 §3.8, realizing the
//! `KeystoreEd25519Signer.securityLevelOf` follow-up).
//!
//! ## What a verified chain proves (D0033 "what attestation proves")
//!
//! Android Key Attestation issues, at key-generation time, a cert chain
//! `leaf (device-key cert, carrying the KeyMint extension)` →
//! `intermediate(s)` → `Google Hardware Attestation Root`. The leaf's
//! extension (OID `1.3.6.1.4.1.11129.2.1.17`, a `KeyDescription`
//! SEQUENCE) is signed by the secure element's attestation key, which
//! chains to Google's root. So a verified chain proves the key was
//! generated by genuine Google-attested `KeyMint` hardware, with the
//! attested properties (security level, origin, purpose, the challenge).
//!
//! It does NOT prove the key is unseizable or the OS is uncompromised —
//! only that the _key material_ is hardware-bound + non-exportable as
//! attested. The `GrapheneOS` verified-boot binding (D0033 §3, Stage 2)
//! extends it to "this is `GrapheneOS` with a locked bootloader"; Stage 1
//! parses + surfaces those `RootOfTrust` fields advisorily (see
//! [`VerifiedBootInfo`]) but does not yet pin them.
//!
//! ## Stage 1 checks (D0033 §2)
//!
//! 1. Parse each DER cert; verify each leaf→…→root link signature with
//!    `x509-parser`'s `ring`-backed `verify_signature`, and each cert's
//!    validity window against `now_unix`.
//! 2. Check the chain terminates at a self-signed cert whose
//!    `SubjectPublicKeyInfo` equals the **pinned Google Hardware
//!    Attestation Root** (`PINNED_GOOGLE_ROOT_SPKI_DER`).
//! 3. Extract + ASN.1-decode the leaf's `KeyMint` `KeyDescription`.
//! 4. Assert: `attestationChallenge == expected_challenge`;
//!    `attestationSecurityLevel ∈ {TrustedEnvironment, StrongBox}`;
//!    hardware-enforced `origin == GENERATED`; hardware-enforced
//!    `purpose ⊇ {SIGN}`.
//!
//! On success returns [`AttestationFacts`]; any failure is a uniform
//! [`AttestationError`] variant carrying indices/tags only (no payload
//! bytes, per D0018 §4.2). The **caller** decides posture: per D0033 §4
//! a failed/absent attestation downgrades the device key to "unattested"
//! and the app keeps running (it falls back to a software key) — the
//! verifier itself is strict (Ok ⟺ all four assertions hold).

// `FromDer` is the single asn1-rs trait both `Any::from_der` and
// `X509Certificate::from_der` resolve through (x509-parser's prelude
// re-exports `asn1_rs::FromDer`); import it once.
use x509_parser::der_parser::asn1_rs::{Any, Class, FromDer, Tag};
use x509_parser::der_parser::oid;
use x509_parser::oid_registry::OID_SIG_ED25519;
use x509_parser::prelude::X509Certificate;

/// The pinned **Google Hardware Attestation Root** `SubjectPublicKeyInfo`
/// (DER), the offline trust anchor for the attestation chain per D0033
/// §2. This is the ECDSA P-384 public key of the self-signed
/// `CN=Key Attestation CA1, O=Google LLC` root. The chain is accepted
/// only if its terminal self-signed cert's SPKI equals these bytes —
/// without this hardcoded pin an attacker could mint their own
/// self-consistent chain rooted in a self-signed cert of their choosing.
///
/// Captured from a real on-device chain (Pixel 6 / `GrapheneOS`, D0033 §1)
/// and cross-checked: 120-byte SPKI, `id-ecPublicKey` / `secp384r1`.
const PINNED_GOOGLE_ROOT_SPKI_DER: [u8; 120] = [
    0x30, 0x76, 0x30, 0x10, 0x06, 0x07, 0x2a, 0x86, 0x48, 0xce, 0x3d, 0x02, //
    0x01, 0x06, 0x05, 0x2b, 0x81, 0x04, 0x00, 0x22, 0x03, 0x62, 0x00, 0x04, //
    0x23, 0xda, 0x23, 0x71, 0x4e, 0xdf, 0x3e, 0x5b, 0x05, 0x0a, 0x3c, 0x72, //
    0xe8, 0x84, 0x6a, 0xce, 0x07, 0x8e, 0xa0, 0xad, 0x1b, 0xf9, 0x8b, 0x15, //
    0xf4, 0x53, 0xd0, 0xcb, 0x08, 0xb2, 0xc3, 0xc1, 0x10, 0x45, 0x39, 0x09, //
    0xf6, 0xed, 0xea, 0xc1, 0xf9, 0xc8, 0xe0, 0x31, 0xa8, 0x48, 0xb9, 0x41, //
    0xa8, 0x29, 0x53, 0x5c, 0x97, 0xe0, 0x7c, 0x27, 0x19, 0xbe, 0xce, 0xb4, //
    0x16, 0x29, 0x0d, 0x30, 0x79, 0xee, 0xe1, 0xf9, 0x11, 0xcc, 0xe6, 0xdf, //
    0x80, 0x39, 0x14, 0xd8, 0xa3, 0x57, 0x7b, 0x34, 0xfd, 0xfd, 0x14, 0x3e, //
    0x5e, 0xf3, 0x6c, 0x97, 0x13, 0xc7, 0xac, 0x70, 0xa8, 0xc2, 0x11, 0xab, //
];

/// Maximum attestation-chain length (leaf + intermediates + root).
/// A real chain is 5 certs; this bounds the walk against a malformed or
/// adversarial over-long chain.
const MAX_CHAIN_LEN: usize = 10;

/// Minimum chain length: a leaf and a (self-signed) root.
const MIN_CHAIN_LEN: usize = 2;

/// The number of top-level fields in a `KeyDescription` SEQUENCE
/// (attestation v3+ layout, stable for `KeyMint`): version, attestation
/// security level, keymaster version, keymaster security level,
/// attestation challenge, unique id, software-enforced, hardware-enforced.
const KEY_DESCRIPTION_MIN_FIELDS: usize = 8;

/// `KeyMint` `purpose` value for signing (`KM_PURPOSE_SIGN`).
const KM_PURPOSE_SIGN: u64 = 2;

/// `KeyMint` `origin` value for an in-hardware-generated key
/// (`KM_ORIGIN_GENERATED`).
const KM_ORIGIN_GENERATED: u64 = 0;

/// `AuthorizationList` context tag for `purpose` (a SET OF INTEGER).
const AUTH_TAG_PURPOSE: u32 = 1;
/// `AuthorizationList` context tag for `origin` (an INTEGER).
const AUTH_TAG_ORIGIN: u32 = 702;
/// `AuthorizationList` context tag for `rootOfTrust` (a SEQUENCE).
const AUTH_TAG_ROOT_OF_TRUST: u32 = 704;

/// The attested security level of the key's secure element (the
/// `attestationSecurityLevel` field of `KeyDescription`).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SecurityLevel {
    /// Software-only (no secure element). Rejected by
    /// [`verify_key_attestation`].
    Software,
    /// Trusted Execution Environment (TEE).
    TrustedEnvironment,
    /// Dedicated secure element (`StrongBox`).
    StrongBox,
}

impl SecurityLevel {
    /// Map the `KeyMint` `SecurityLevel` ENUMERATED value.
    const fn from_enum(value: u64) -> Option<Self> {
        match value {
            0 => Some(Self::Software),
            1 => Some(Self::TrustedEnvironment),
            2 => Some(Self::StrongBox),
            _ => None,
        }
    }

    /// Whether this level is a hardware-backed secure element (TEE or
    /// `StrongBox`) — the D0033 §2 acceptance set.
    #[must_use]
    pub const fn is_hardware(self) -> bool {
        matches!(self, Self::TrustedEnvironment | Self::StrongBox)
    }
}

/// The verified-boot state from the leaf's `RootOfTrust` (D0033 §3).
/// Parsed + surfaced advisorily in Stage 1; pinned in Stage 2.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum VerifiedBootState {
    /// Boot chain verified against the device's configured root of trust.
    Verified,
    /// Boot chain verified against a user-installed key (e.g. `GrapheneOS`
    /// with a locked bootloader + a self-installed AVB key).
    SelfSigned,
    /// Boot was not verified.
    Unverified,
    /// Boot verification failed.
    Failed,
}

impl VerifiedBootState {
    const fn from_enum(value: u64) -> Option<Self> {
        match value {
            0 => Some(Self::Verified),
            1 => Some(Self::SelfSigned),
            2 => Some(Self::Unverified),
            3 => Some(Self::Failed),
            _ => None,
        }
    }
}

/// Advisory verified-boot facts from the leaf `RootOfTrust` (D0033 §3).
///
/// NOT asserted in Stage 1; the `GrapheneOS` `verifiedBootKey` pin +
/// `deviceLocked` / `verifiedBootState` assertion is Stage 2.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct VerifiedBootInfo {
    /// Whether the bootloader is locked (`deviceLocked`).
    pub device_locked: bool,
    /// The verified-boot state.
    pub verified_boot_state: VerifiedBootState,
    /// The `verifiedBootKey` digest — the AVB key fingerprint. Carried
    /// so Stage 2 can pin the `GrapheneOS` key without re-parsing.
    pub verified_boot_key: Vec<u8>,
}

/// The facts a verified attestation establishes (D0033 §2). Returned by
/// [`verify_key_attestation`] only when all four §2 assertions hold.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AttestationFacts {
    /// The `KeyMint` `attestationVersion` (e.g. 400 for `KeyMint`).
    pub attestation_version: u32,
    /// The attested security level — guaranteed `TrustedEnvironment` or
    /// `StrongBox` (Software is rejected).
    pub security_level: SecurityLevel,
    /// Always `true` on the Ok path: hardware-enforced
    /// `origin == GENERATED` (key minted in-hardware, not imported).
    pub origin_generated: bool,
    /// Always `true` on the Ok path: hardware-enforced
    /// `purpose ⊇ {SIGN}`.
    pub purpose_sign: bool,
    /// The leaf cert's Ed25519 device public key (32 bytes), when the
    /// leaf SPKI is Ed25519 (the Cairn device key always is). The caller
    /// can cross-check this equals the device key it expects, binding
    /// the attestation to a specific key. `None` if the leaf SPKI is not
    /// Ed25519.
    pub device_public_key: Option<Vec<u8>>,
    /// Advisory verified-boot facts (D0033 §3). `None` if absent or
    /// unparseable — Stage 1 never fails the verification on these.
    pub verified_boot: Option<VerifiedBootInfo>,
}

/// Why an attestation chain failed to verify. Variants carry indices /
/// tags only — never certificate or key bytes — per D0018 §4.2.
///
/// `#[non_exhaustive]` so Stage 2 (verified-boot pinning, revocation)
/// can add variants without a major bump.
#[derive(Debug, Clone, PartialEq, Eq)]
#[non_exhaustive]
pub enum AttestationError {
    /// The chain was empty.
    EmptyChain,
    /// The chain had fewer than `MIN_CHAIN_LEN` certs.
    TooFewCertificates {
        /// Number of certs supplied.
        got: usize,
    },
    /// The chain had more than `MAX_CHAIN_LEN` certs.
    ChainTooLong {
        /// Number of certs supplied.
        got: usize,
    },
    /// Certificate at `index` (leaf = 0) did not parse as DER X.509.
    MalformedCertificate {
        /// Position in the chain (leaf-first).
        index: usize,
    },
    /// Certificate at `index` was outside its validity window at
    /// `now_unix`.
    ValidityWindowFailed {
        /// Position in the chain (leaf-first).
        index: usize,
    },
    /// The cert at `index` claims an issuer DN that does not match the
    /// subject DN of the next cert in the chain.
    IssuerSubjectMismatch {
        /// Position of the child cert in the chain (leaf-first).
        index: usize,
    },
    /// The signature on the cert at `index` did not verify against the
    /// next cert's public key (or, for the root, its own).
    LinkSignatureInvalid {
        /// Position of the child cert in the chain (leaf-first).
        index: usize,
    },
    /// The terminal cert is not self-signed (subject ≠ issuer), so it
    /// cannot be a trust-anchor root.
    RootNotSelfSigned,
    /// The terminal cert's `SubjectPublicKeyInfo` does not equal the
    /// pinned Google Hardware Attestation Root.
    RootNotPinned,
    /// The leaf carried no `KeyMint` attestation extension (OID
    /// `1.3.6.1.4.1.11129.2.1.17`) — the key was generated without a
    /// challenge, so no real chain exists.
    MissingKeymintExtension,
    /// The `KeyMint` extension was present but its `KeyDescription` ASN.1
    /// did not decode to the expected structure.
    MalformedKeymintExtension,
    /// The attested `attestationChallenge` did not equal the expected
    /// challenge — the chain does not bind our freshness nonce.
    ChallengeMismatch,
    /// The attested `attestationSecurityLevel` was `Software` — not a
    /// hardware-backed secure element.
    SecurityLevelTooLow,
    /// The hardware-enforced `origin` was not `GENERATED` — the key was
    /// imported or derived, not minted in-hardware.
    OriginNotGenerated,
    /// The hardware-enforced `purpose` set did not include `SIGN`.
    PurposeMissingSign,
}

impl core::fmt::Display for AttestationError {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::EmptyChain => write!(f, "attestation chain is empty"),
            Self::TooFewCertificates { got } => {
                write!(f, "attestation chain too short: {got} cert(s)")
            }
            Self::ChainTooLong { got } => write!(f, "attestation chain too long: {got} certs"),
            Self::MalformedCertificate { index } => {
                write!(f, "attestation cert {index} did not parse")
            }
            Self::ValidityWindowFailed { index } => {
                write!(f, "attestation cert {index} outside its validity window")
            }
            Self::IssuerSubjectMismatch { index } => {
                write!(f, "attestation cert {index} issuer/subject mismatch")
            }
            Self::LinkSignatureInvalid { index } => {
                write!(f, "attestation cert {index} signature did not verify")
            }
            Self::RootNotSelfSigned => write!(f, "attestation root is not self-signed"),
            Self::RootNotPinned => {
                write!(f, "attestation root is not the pinned Google root")
            }
            Self::MissingKeymintExtension => {
                write!(f, "leaf has no `KeyMint` attestation extension")
            }
            Self::MalformedKeymintExtension => write!(f, "`KeyMint` KeyDescription malformed"),
            Self::ChallengeMismatch => write!(f, "attestation challenge mismatch"),
            Self::SecurityLevelTooLow => write!(f, "attestation security level is software-only"),
            Self::OriginNotGenerated => write!(f, "attested key origin is not GENERATED"),
            Self::PurposeMissingSign => write!(f, "attested key purpose does not include SIGN"),
        }
    }
}

impl core::error::Error for AttestationError {}

/// Verify an Android Key Attestation chain per D0033 §2 (Stage 1).
///
/// `chain` is the DER-encoded cert chain, **leaf-first**, exactly as
/// Android `KeyStore.getCertificateChain` returns it (leaf → … →
/// self-signed Google root). `expected_challenge` is the 32-byte
/// freshness nonce embedded at key-generation. `now_unix` is the current
/// time (seconds) for the validity-window checks.
///
/// # Errors
///
/// Returns an [`AttestationError`] if any §2 check fails: a malformed or
/// expired cert, a broken signature link, a chain not rooted in the
/// pinned Google root, a missing/malformed `KeyMint` extension, a
/// challenge mismatch, a software-only security level, a non-`GENERATED`
/// origin, or a `purpose` set lacking `SIGN`.
pub fn verify_key_attestation(
    chain: &[Vec<u8>],
    expected_challenge: &[u8],
    now_unix: u64,
) -> Result<AttestationFacts, AttestationError> {
    if chain.is_empty() {
        return Err(AttestationError::EmptyChain);
    }
    if chain.len() < MIN_CHAIN_LEN {
        return Err(AttestationError::TooFewCertificates { got: chain.len() });
    }
    if chain.len() > MAX_CHAIN_LEN {
        return Err(AttestationError::ChainTooLong { got: chain.len() });
    }

    // Parse every cert up front (leaf-first). Keep them in a Vec so the
    // borrow lasts for the whole chain walk.
    let certs: Vec<X509Certificate> = chain
        .iter()
        .enumerate()
        .map(|(index, der)| {
            X509Certificate::from_der(der)
                .map(|(_, cert)| cert)
                .map_err(|_| AttestationError::MalformedCertificate { index })
        })
        .collect::<Result<_, _>>()?;

    // (1) Validity windows: every cert must be valid at `now_unix`.
    let now =
        i64::try_from(now_unix).map_err(|_| AttestationError::ValidityWindowFailed { index: 0 })?;
    for (index, cert) in certs.iter().enumerate() {
        let not_before = cert.validity().not_before.timestamp();
        let not_after = cert.validity().not_after.timestamp();
        if now < not_before || now > not_after {
            return Err(AttestationError::ValidityWindowFailed { index });
        }
    }

    // (1) Signature links: each child must be signed by the next cert's
    // key, and the child's issuer DN must equal the parent's subject DN.
    for (index, pair) in certs.windows(2).enumerate() {
        let [child, parent] = pair else {
            // windows(2) always yields len-2 slices; defensive only.
            return Err(AttestationError::LinkSignatureInvalid { index });
        };
        if child.issuer() != parent.subject() {
            return Err(AttestationError::IssuerSubjectMismatch { index });
        }
        child
            .verify_signature(Some(parent.public_key()))
            .map_err(|_| AttestationError::LinkSignatureInvalid { index })?;
    }

    // (2) The terminal cert must be a self-signed root that equals the
    // pinned Google Hardware Attestation Root.
    let root_index = certs.len().saturating_sub(1);
    let root = certs
        .last()
        .ok_or(AttestationError::TooFewCertificates { got: certs.len() })?;
    if root.subject() != root.issuer() {
        return Err(AttestationError::RootNotSelfSigned);
    }
    root.verify_signature(Some(root.public_key()))
        .map_err(|_| AttestationError::LinkSignatureInvalid { index: root_index })?;
    if root.public_key().raw != PINNED_GOOGLE_ROOT_SPKI_DER {
        return Err(AttestationError::RootNotPinned);
    }

    // (3) + (4) Parse the leaf's `KeyMint` extension + assert the four
    // §2 properties.
    let leaf = certs.first().ok_or(AttestationError::EmptyChain)?;
    let key_desc = leaf_keymint_extension(leaf)?;
    let parsed = parse_key_description(key_desc)?;

    if parsed.challenge != expected_challenge {
        return Err(AttestationError::ChallengeMismatch);
    }
    if !parsed.security_level.is_hardware() {
        return Err(AttestationError::SecurityLevelTooLow);
    }
    if !parsed.origin_generated {
        return Err(AttestationError::OriginNotGenerated);
    }
    if !parsed.purpose_sign {
        return Err(AttestationError::PurposeMissingSign);
    }

    Ok(AttestationFacts {
        attestation_version: parsed.attestation_version,
        security_level: parsed.security_level,
        origin_generated: parsed.origin_generated,
        purpose_sign: parsed.purpose_sign,
        device_public_key: leaf_ed25519_key(leaf),
        verified_boot: parsed.verified_boot,
    })
}

/// Pull the `KeyMint` `KeyDescription` DER (the extnValue content) from the
/// leaf's `1.3.6.1.4.1.11129.2.1.17` extension.
fn leaf_keymint_extension<'a>(leaf: &'a X509Certificate<'a>) -> Result<&'a [u8], AttestationError> {
    let keymint_oid = oid!(1.3.6.1.4.1.11129.2.1.17);
    let ext = leaf
        .get_extension_unique(&keymint_oid)
        .map_err(|_| AttestationError::MalformedKeymintExtension)?
        .ok_or(AttestationError::MissingKeymintExtension)?;
    Ok(ext.value)
}

/// Extract the leaf's Ed25519 device public key (32 bytes), if the leaf
/// SPKI is Ed25519. Best-effort: returns `None` for any other key type.
fn leaf_ed25519_key(leaf: &X509Certificate) -> Option<Vec<u8>> {
    let spki = leaf.public_key();
    if spki.algorithm.algorithm != OID_SIG_ED25519 {
        return None;
    }
    let key = spki.subject_public_key.data.as_ref();
    if key.len() == 32 {
        Some(key.to_vec())
    } else {
        None
    }
}

/// The fields extracted from a `KeyDescription` before the §2 assertions.
struct ParsedKeyDescription<'a> {
    attestation_version: u32,
    security_level: SecurityLevel,
    challenge: &'a [u8],
    origin_generated: bool,
    purpose_sign: bool,
    verified_boot: Option<VerifiedBootInfo>,
}

/// Decode the `KeyMint` `KeyDescription` SEQUENCE (D0033 §2 step 3).
///
/// The top-level fields are a fixed, ordered SEQUENCE so they are read
/// positionally; the `AuthorizationList` entries are sparse EXPLICIT
/// context-tagged optionals so they are matched by tag number.
fn parse_key_description(der: &[u8]) -> Result<ParsedKeyDescription<'_>, AttestationError> {
    // `der` is the KeyDescription SEQUENCE TLV (the extnValue content);
    // unwrap it to its content before iterating the ordered fields.
    let outer = der_single_element(der)?;
    if outer.header.tag() != Tag::Sequence {
        return Err(AttestationError::MalformedKeymintExtension);
    }
    let fields = der_sequence_elements(outer.data)?;
    if fields.len() < KEY_DESCRIPTION_MIN_FIELDS {
        return Err(AttestationError::MalformedKeymintExtension);
    }

    // [0] attestationVersion (INTEGER)
    let attestation_version =
        u32::try_from(read_universal_uint(field_at(&fields, 0)?, Tag::Integer)?)
            .map_err(|_| AttestationError::MalformedKeymintExtension)?;

    // [1] attestationSecurityLevel (ENUMERATED)
    let sec_value = read_universal_uint(field_at(&fields, 1)?, Tag::Enumerated)?;
    let security_level =
        SecurityLevel::from_enum(sec_value).ok_or(AttestationError::MalformedKeymintExtension)?;

    // [4] attestationChallenge (OCTET STRING)
    let challenge_any = field_at(&fields, 4)?;
    if challenge_any.header.tag() != Tag::OctetString {
        return Err(AttestationError::MalformedKeymintExtension);
    }
    let challenge = challenge_any.data;

    // [7] hardwareEnforced (SEQUENCE of EXPLICIT context-tagged entries)
    let hw = field_at(&fields, 7)?;
    if hw.header.tag() != Tag::Sequence {
        return Err(AttestationError::MalformedKeymintExtension);
    }
    let (origin_generated, purpose_sign, verified_boot) = parse_authorization_list(hw.data)?;

    Ok(ParsedKeyDescription {
        attestation_version,
        security_level,
        challenge,
        origin_generated,
        purpose_sign,
        verified_boot,
    })
}

/// Walk a hardware-enforced `AuthorizationList`, extracting the
/// asserted-on tags ([`AUTH_TAG_ORIGIN`], [`AUTH_TAG_PURPOSE`]) and the
/// advisory `RootOfTrust` ([`AUTH_TAG_ROOT_OF_TRUST`]).
///
/// Returns `(origin_generated, purpose_sign, verified_boot)`. Absent tags
/// yield `false` / `None` — the caller turns a missing `origin`/`purpose`
/// into the appropriate §4 rejection.
fn parse_authorization_list(
    der: &[u8],
) -> Result<(bool, bool, Option<VerifiedBootInfo>), AttestationError> {
    let entries = der_sequence_elements(der)?;
    let mut origin_generated = false;
    let mut purpose_sign = false;
    let mut verified_boot = None;

    for entry in &entries {
        // AuthorizationList entries are EXPLICIT [tag] context-specific.
        if entry.header.class() != Class::ContextSpecific {
            continue;
        }
        match entry.header.tag().0 {
            AUTH_TAG_PURPOSE => {
                // EXPLICIT wrap → inner SET OF INTEGER.
                let inner = der_single_element(entry.data)?;
                if inner.header.tag() != Tag::Set {
                    return Err(AttestationError::MalformedKeymintExtension);
                }
                for int_any in der_sequence_elements(inner.data)? {
                    if int_any.header.tag() == Tag::Integer
                        && read_uint_bytes(int_any.data) == Some(KM_PURPOSE_SIGN)
                    {
                        purpose_sign = true;
                    }
                }
            }
            AUTH_TAG_ORIGIN => {
                // EXPLICIT wrap → inner INTEGER.
                let inner = der_single_element(entry.data)?;
                if inner.header.tag() == Tag::Integer
                    && read_uint_bytes(inner.data) == Some(KM_ORIGIN_GENERATED)
                {
                    origin_generated = true;
                }
            }
            AUTH_TAG_ROOT_OF_TRUST => {
                // Advisory (D0033 §3): best-effort, never fail on this.
                verified_boot = parse_root_of_trust(entry.data).ok();
            }
            _ => {}
        }
    }

    Ok((origin_generated, purpose_sign, verified_boot))
}

/// Parse the `RootOfTrust` SEQUENCE (D0033 §3, advisory). The EXPLICIT
/// [704] wrap's content is a SEQUENCE:
/// `{ verifiedBootKey OCTET STRING, deviceLocked BOOLEAN,
///    verifiedBootState ENUMERATED, verifiedBootHash OCTET STRING }`.
fn parse_root_of_trust(explicit_inner: &[u8]) -> Result<VerifiedBootInfo, AttestationError> {
    let seq = der_single_element(explicit_inner)?;
    if seq.header.tag() != Tag::Sequence {
        return Err(AttestationError::MalformedKeymintExtension);
    }
    let parts = der_sequence_elements(seq.data)?;
    let key_any = field_at(&parts, 0)?;
    if key_any.header.tag() != Tag::OctetString {
        return Err(AttestationError::MalformedKeymintExtension);
    }
    let locked_any = field_at(&parts, 1)?;
    // BOOLEAN content: 0x00 = false, anything else = true.
    let device_locked = locked_any.data.first().is_some_and(|&b| b != 0x00);
    let state_value = read_universal_uint(field_at(&parts, 2)?, Tag::Enumerated)?;
    let verified_boot_state = VerifiedBootState::from_enum(state_value)
        .ok_or(AttestationError::MalformedKeymintExtension)?;

    Ok(VerifiedBootInfo {
        device_locked,
        verified_boot_state,
        verified_boot_key: key_any.data.to_vec(),
    })
}

/// Parse a DER buffer as a flat sequence of TLV elements (the content of
/// a SEQUENCE/SET). Errors if any element is malformed or trailing bytes
/// remain that do not form a complete element.
fn der_sequence_elements(mut input: &[u8]) -> Result<Vec<Any<'_>>, AttestationError> {
    let mut out = Vec::new();
    while !input.is_empty() {
        let (rem, any) =
            Any::from_der(input).map_err(|_| AttestationError::MalformedKeymintExtension)?;
        out.push(any);
        input = rem;
    }
    Ok(out)
}

/// Parse exactly one DER TLV element from the front of `input` (used to
/// unwrap an EXPLICIT context tag's inner element).
fn der_single_element(input: &[u8]) -> Result<Any<'_>, AttestationError> {
    let (_, any) = Any::from_der(input).map_err(|_| AttestationError::MalformedKeymintExtension)?;
    Ok(any)
}

/// Borrow the `idx`-th element of a parsed field list, or error.
fn field_at<'b, 'a>(fields: &'b [Any<'a>], idx: usize) -> Result<&'b Any<'a>, AttestationError> {
    fields
        .get(idx)
        .ok_or(AttestationError::MalformedKeymintExtension)
}

/// Read a small unsigned integer from a universal-tagged element,
/// asserting its tag.
fn read_universal_uint(any: &Any, expected: Tag) -> Result<u64, AttestationError> {
    if any.header.tag() != expected {
        return Err(AttestationError::MalformedKeymintExtension);
    }
    read_uint_bytes(any.data).ok_or(AttestationError::MalformedKeymintExtension)
}

/// Interpret up to 8 big-endian content bytes as an unsigned integer.
/// DER INTEGER content may carry a leading `0x00` sign byte (e.g. keySize
/// `0x0100` = 256); this folds it in. Returns `None` for empty or
/// over-wide (> 8 byte) content.
fn read_uint_bytes(data: &[u8]) -> Option<u64> {
    if data.is_empty() || data.len() > 8 {
        return None;
    }
    let mut value: u64 = 0;
    for &b in data {
        value = (value << 8) | u64::from(b);
    }
    Some(value)
}

#[cfg(test)]
#[allow(clippy::indexing_slicing, clippy::panic, clippy::unwrap_used)]
mod tests {
    use super::*;

    // The real on-device chain captured per D0033 §1 (Pixel 6 /
    // `GrapheneOS`): leaf (Ed25519 device key, `KeyMint` ext) → TEE batch
    // intermediate → Droid CA3 → Droid CA2 → self-signed Google root.
    const CERT_0: &[u8] = include_bytes!("../tests/vectors/attestation/cert-0.der");
    const CERT_1: &[u8] = include_bytes!("../tests/vectors/attestation/cert-1.der");
    const CERT_2: &[u8] = include_bytes!("../tests/vectors/attestation/cert-2.der");
    const CERT_3: &[u8] = include_bytes!("../tests/vectors/attestation/cert-3.der");
    const CERT_4: &[u8] = include_bytes!("../tests/vectors/attestation/cert-4.der");
    const CHALLENGE: &[u8] = include_bytes!("../tests/vectors/attestation/challenge.bin");

    // A FIXED timestamp inside every cert's validity window at capture
    // time (2026-06-04 12:00 UTC). The leaf is 1970→2048, but the TEE
    // batch intermediate (cert-1) is short-lived — Jun 1→Jun 14 2026 —
    // so the test pins capture-time, not wall-clock "now" (which would
    // make the vector expire ~2 weeks after capture). This mirrors the
    // production model (D0033 §1): verify once near key-generation, then
    // persist the facts; do not re-walk an expired chain later.
    const NOW: u64 = 1_780_574_400;

    fn real_chain() -> Vec<Vec<u8>> {
        vec![
            CERT_0.to_vec(),
            CERT_1.to_vec(),
            CERT_2.to_vec(),
            CERT_3.to_vec(),
            CERT_4.to_vec(),
        ]
    }

    #[test]
    fn accepts_real_chain_and_extracts_facts() {
        let facts = verify_key_attestation(&real_chain(), CHALLENGE, NOW)
            .expect("real captured chain must verify");
        // The Pixel 6 device key is TEE-backed (D0033 §1 on-device proof).
        assert_eq!(facts.security_level, SecurityLevel::TrustedEnvironment);
        assert!(facts.security_level.is_hardware());
        assert!(facts.origin_generated);
        assert!(facts.purpose_sign);
        assert_eq!(facts.attestation_version, 400);
        // The leaf binds the 32-byte Ed25519 device key.
        let dev = facts.device_public_key.expect("leaf is Ed25519");
        assert_eq!(dev.len(), 32);
        // Verified-boot facts are surfaced advisorily (D0033 §3).
        let vb = facts.verified_boot.expect("RootOfTrust present");
        assert!(vb.device_locked);
        assert_eq!(vb.verified_boot_key.len(), 32);
    }

    #[test]
    fn rejects_wrong_challenge() {
        let mut wrong = CHALLENGE.to_vec();
        wrong[0] ^= 0xFF;
        let result = verify_key_attestation(&real_chain(), &wrong, NOW);
        assert_eq!(result, Err(AttestationError::ChallengeMismatch));
    }

    #[test]
    fn rejects_challenge_length_mismatch() {
        let result = verify_key_attestation(&real_chain(), b"short", NOW);
        assert_eq!(result, Err(AttestationError::ChallengeMismatch));
    }

    #[test]
    fn rejects_truncated_chain_missing_root() {
        // Drop the real Google root: present leaf→…→CA2 with CA2 (cert-3)
        // as the terminal. CA2 is not self-signed, so the self-signed
        // gate trips before the pin check — there is no self-signed
        // terminal to reach without the real root.
        let truncated = vec![
            CERT_0.to_vec(),
            CERT_1.to_vec(),
            CERT_2.to_vec(),
            CERT_3.to_vec(),
        ];
        let result = verify_key_attestation(&truncated, CHALLENGE, NOW);
        assert_eq!(result, Err(AttestationError::RootNotSelfSigned));
    }

    #[test]
    fn rejects_valid_chain_with_unpinned_root() {
        // THE pin test (D0033 §2): a fully self-consistent 2-cert chain
        // whose links verify and whose terminal IS self-signed — but the
        // root SPKI is NOT the pinned Google root. Without the hardcoded
        // pin an attacker could mint exactly this. Must be RootNotPinned.
        let (leaf_der, root_der) = synthetic::unpinned_chain();
        let chain = vec![leaf_der, root_der];
        let result = verify_key_attestation(&chain, CHALLENGE, NOW);
        assert_eq!(result, Err(AttestationError::RootNotPinned));
    }

    #[test]
    fn rejects_broken_signature_link() {
        // Flip a byte deep in the leaf TBS so its issuer signature no
        // longer verifies (or the DER no longer parses). Byte 300 is well
        // inside the TBSCertificate, past the structural header.
        let mut chain = real_chain();
        chain[0][300] ^= 0x01;
        let result = verify_key_attestation(&chain, CHALLENGE, NOW);
        assert!(
            matches!(
                result,
                Err(AttestationError::LinkSignatureInvalid { index: 0 }
                    | AttestationError::MalformedCertificate { index: 0 }
                    | AttestationError::IssuerSubjectMismatch { index: 0 })
            ),
            "expected a leaf-level rejection, got {result:?}"
        );
    }

    #[test]
    fn rejects_expired_window() {
        // A time far past every cert not_after (year ~2200).
        let result = verify_key_attestation(&real_chain(), CHALLENGE, 7_258_118_400);
        assert!(matches!(
            result,
            Err(AttestationError::ValidityWindowFailed { .. })
        ));
    }

    #[test]
    fn rejects_before_intermediate_window() {
        // A time BEFORE the short-lived batch intermediate's not_before
        // (early 2026) — cert-1 is not yet valid, so index 1 trips.
        let result = verify_key_attestation(&real_chain(), CHALLENGE, 1_700_000_000);
        assert_eq!(
            result,
            Err(AttestationError::ValidityWindowFailed { index: 1 })
        );
    }

    #[test]
    fn rejects_empty_and_short_chains() {
        assert_eq!(
            verify_key_attestation(&[], CHALLENGE, NOW),
            Err(AttestationError::EmptyChain)
        );
        assert_eq!(
            verify_key_attestation(&[CERT_0.to_vec()], CHALLENGE, NOW),
            Err(AttestationError::TooFewCertificates { got: 1 })
        );
    }

    #[test]
    fn rejects_overlong_chain() {
        let over: Vec<Vec<u8>> = (0..=MAX_CHAIN_LEN).map(|_| CERT_0.to_vec()).collect();
        assert_eq!(
            verify_key_attestation(&over, CHALLENGE, NOW),
            Err(AttestationError::ChainTooLong {
                got: MAX_CHAIN_LEN + 1
            })
        );
    }

    #[test]
    fn rejects_malformed_leaf_der() {
        let chain = vec![b"\xFF\x00 not a cert".to_vec(), CERT_4.to_vec()];
        assert_eq!(
            verify_key_attestation(&chain, CHALLENGE, NOW),
            Err(AttestationError::MalformedCertificate { index: 0 })
        );
    }

    #[test]
    fn security_level_mapping() {
        assert_eq!(SecurityLevel::from_enum(0), Some(SecurityLevel::Software));
        assert_eq!(
            SecurityLevel::from_enum(1),
            Some(SecurityLevel::TrustedEnvironment)
        );
        assert_eq!(SecurityLevel::from_enum(2), Some(SecurityLevel::StrongBox));
        assert_eq!(SecurityLevel::from_enum(3), None);
        assert!(!SecurityLevel::Software.is_hardware());
        assert!(SecurityLevel::TrustedEnvironment.is_hardware());
        assert!(SecurityLevel::StrongBox.is_hardware());
    }

    #[test]
    fn uint_reader_folds_sign_byte() {
        // keySize 0x0100 = 256, with a leading sign byte.
        assert_eq!(read_uint_bytes(&[0x01, 0x00]), Some(256));
        assert_eq!(read_uint_bytes(&[0x00]), Some(0));
        assert_eq!(read_uint_bytes(&[0x90]), Some(0x90));
        assert_eq!(read_uint_bytes(&[]), None);
        assert_eq!(read_uint_bytes(&[0; 9]), None);
    }

    // ===================================================================
    // `KeyMint` `KeyDescription` decode — the highest-risk ASN.1 surface
    // (D0033 §2), unit-tested directly against `parse_key_description`
    // with hand-built DER so the security-level / origin / purpose /
    // challenge extraction is exercised without needing to forge a
    // pinned-root chain.
    // ===================================================================

    #[test]
    fn decodes_real_extension_fields() {
        // Extract the `KeyMint` extension straight from the real leaf and
        // decode it: the positive path through `parse_key_description`.
        let (_, leaf) = X509Certificate::from_der(CERT_0).unwrap();
        let kd = leaf_keymint_extension(&leaf).unwrap();
        let parsed = parse_key_description(kd).unwrap();
        assert_eq!(parsed.attestation_version, 400);
        assert_eq!(parsed.security_level, SecurityLevel::TrustedEnvironment);
        assert_eq!(parsed.challenge, CHALLENGE);
        assert!(parsed.origin_generated);
        assert!(parsed.purpose_sign);
        assert!(parsed.verified_boot.is_some());
    }

    #[test]
    fn decodes_software_level() {
        let kd = synthetic::key_description(0, KM_ORIGIN_GENERATED, &[KM_PURPOSE_SIGN], CHALLENGE);
        let parsed = parse_key_description(&kd).unwrap();
        assert_eq!(parsed.security_level, SecurityLevel::Software);
        assert!(!parsed.security_level.is_hardware());
    }

    #[test]
    fn decodes_strongbox_level() {
        let kd = synthetic::key_description(2, KM_ORIGIN_GENERATED, &[KM_PURPOSE_SIGN], CHALLENGE);
        let parsed = parse_key_description(&kd).unwrap();
        assert_eq!(parsed.security_level, SecurityLevel::StrongBox);
    }

    #[test]
    fn decodes_imported_origin_as_not_generated() {
        // origin = 2 (KM_ORIGIN_IMPORTED) → origin_generated stays false.
        let kd = synthetic::key_description(1, 2, &[KM_PURPOSE_SIGN], CHALLENGE);
        let parsed = parse_key_description(&kd).unwrap();
        assert!(!parsed.origin_generated);
    }

    #[test]
    fn decodes_purpose_without_sign() {
        // purpose = {VERIFY(3)} only → purpose_sign stays false.
        let kd = synthetic::key_description(1, KM_ORIGIN_GENERATED, &[3], CHALLENGE);
        let parsed = parse_key_description(&kd).unwrap();
        assert!(!parsed.purpose_sign);
    }

    #[test]
    fn decodes_multi_purpose_including_sign() {
        // purpose = {SIGN(2), VERIFY(3)} → purpose_sign true.
        let kd =
            synthetic::key_description(1, KM_ORIGIN_GENERATED, &[KM_PURPOSE_SIGN, 3], CHALLENGE);
        let parsed = parse_key_description(&kd).unwrap();
        assert!(parsed.purpose_sign);
    }

    #[test]
    fn rejects_truncated_key_description() {
        // A SEQUENCE with fewer than 8 fields is malformed.
        let too_short = synthetic::tlv(0x30, &synthetic::tlv(0x02, &[0x01]));
        assert!(matches!(
            parse_key_description(&too_short),
            Err(AttestationError::MalformedKeymintExtension)
        ));
    }

    #[test]
    fn rejects_unknown_security_level_enum() {
        // ENUMERATED value 7 is not a defined SecurityLevel.
        let kd = synthetic::key_description(7, KM_ORIGIN_GENERATED, &[KM_PURPOSE_SIGN], CHALLENGE);
        assert!(matches!(
            parse_key_description(&kd),
            Err(AttestationError::MalformedKeymintExtension)
        ));
    }

    /// Synthetic DER builders for the decode tests + the pin test. These
    /// produce *only* test inputs — never anything the verifier trusts.
    ///
    /// The `len as u8` casts are guarded by the surrounding length-form
    /// branches (a DER short/0x81 length byte is < 256 by construction),
    /// so the truncation is intentional and test-local.
    #[allow(clippy::cast_possible_truncation)]
    mod synthetic {
        use rcgen::{
            BasicConstraints, CertificateParams, DnType, IsCa, KeyPair, PKCS_ECDSA_P384_SHA384,
            date_time_ymd,
        };

        /// Encode a single DER TLV with a one-byte tag, handling the
        /// short (< 128), one-byte-long (< 256), and two-byte-long
        /// length forms.
        pub(super) fn tlv(tag: u8, body: &[u8]) -> Vec<u8> {
            let mut v = vec![tag];
            let len = body.len();
            if len < 0x80 {
                v.push(len as u8);
            } else if len < 0x100 {
                v.push(0x81);
                v.push(len as u8);
            } else {
                v.push(0x82);
                v.push((len >> 8) as u8);
                v.push((len & 0xFF) as u8);
            }
            v.extend_from_slice(body);
            v
        }

        /// Encode a context-specific constructed (EXPLICIT) tag header,
        /// using the high-tag-number form for tags ≥ 31 (e.g. [702]).
        fn ctx_tag_bytes(num: u32) -> Vec<u8> {
            if num < 31 {
                return vec![0xA0 | (num as u8)];
            }
            let mut stack = vec![(num & 0x7F) as u8];
            let mut n = num >> 7;
            while n > 0 {
                stack.push(((n & 0x7F) as u8) | 0x80);
                n >>= 7;
            }
            stack.reverse();
            let mut out = vec![0xBF];
            out.extend_from_slice(&stack);
            out
        }

        /// Wrap `inner` in an EXPLICIT context tag `num`. Inner bodies in
        /// these tests are always < 256 bytes (short or 0x81 length form).
        fn ctx_explicit(num: u32, inner: &[u8]) -> Vec<u8> {
            let mut v = ctx_tag_bytes(num);
            let len = inner.len();
            if len >= 0x80 {
                v.push(0x81);
            }
            v.push(len as u8);
            v.extend_from_slice(inner);
            v
        }

        fn integer(value: u64) -> Vec<u8> {
            // Minimal big-endian; 0 encodes as a single 0x00 byte.
            if value == 0 {
                return tlv(0x02, &[0x00]);
            }
            let mut bytes = value.to_be_bytes().to_vec();
            while bytes.first() == Some(&0x00) {
                bytes.remove(0);
            }
            tlv(0x02, &bytes)
        }

        /// Build a `KeyMint` `KeyDescription` SEQUENCE with the given
        /// attestation security level (ENUMERATED), hardware-enforced
        /// origin, hardware-enforced purpose set, and challenge.
        pub(super) fn key_description(
            sec_level: u8,
            origin: u64,
            purposes: &[u64],
            challenge: &[u8],
        ) -> Vec<u8> {
            // hardwareEnforced AuthorizationList: [1] purpose (SET OF
            // INTEGER) then [702] origin (INTEGER).
            let purpose_set: Vec<u8> = {
                let mut ints = Vec::new();
                for &p in purposes {
                    ints.extend_from_slice(&integer(p));
                }
                tlv(0x31, &ints) // SET
            };
            let mut hw = Vec::new();
            hw.extend_from_slice(&ctx_explicit(1, &purpose_set));
            hw.extend_from_slice(&ctx_explicit(702, &integer(origin)));
            let hw_seq = tlv(0x30, &hw);

            let mut kd = Vec::new();
            kd.extend_from_slice(&integer(400)); // [0] attestationVersion
            kd.extend_from_slice(&tlv(0x0A, &[sec_level])); // [1] secLevel ENUM
            kd.extend_from_slice(&integer(400)); // [2] keymasterVersion
            kd.extend_from_slice(&tlv(0x0A, &[sec_level])); // [3] kmSecLevel
            kd.extend_from_slice(&tlv(0x04, challenge)); // [4] challenge OCTET
            kd.extend_from_slice(&tlv(0x04, &[])); // [5] uniqueId OCTET (empty)
            kd.extend_from_slice(&tlv(0x30, &[])); // [6] softwareEnforced (empty)
            kd.extend_from_slice(&hw_seq); // [7] hardwareEnforced
            tlv(0x30, &kd)
        }

        /// A self-signed P-384 root + a leaf signed by it, both valid in
        /// 2020–2030. The links verify and the root is self-signed, but
        /// the root SPKI is NOT the pinned Google root — the input for
        /// the `RootNotPinned` pin test. Returns `(leaf_der, root_der)`.
        pub(super) fn unpinned_chain() -> (Vec<u8>, Vec<u8>) {
            let root_key = KeyPair::generate_for(&PKCS_ECDSA_P384_SHA384).unwrap();
            let mut root_params = CertificateParams::default();
            root_params.is_ca = IsCa::Ca(BasicConstraints::Unconstrained);
            root_params.not_before = date_time_ymd(2020, 1, 1);
            root_params.not_after = date_time_ymd(2030, 1, 1);
            root_params
                .distinguished_name
                .push(DnType::CommonName, "Not The Google Root");
            let root = root_params.self_signed(&root_key).unwrap();

            let leaf_key = KeyPair::generate_for(&PKCS_ECDSA_P384_SHA384).unwrap();
            let mut leaf_params = CertificateParams::default();
            leaf_params.is_ca = IsCa::NoCa;
            leaf_params.not_before = date_time_ymd(2020, 1, 1);
            leaf_params.not_after = date_time_ymd(2030, 1, 1);
            leaf_params
                .distinguished_name
                .push(DnType::CommonName, "Synthetic Leaf");
            let leaf = leaf_params.signed_by(&leaf_key, &root, &root_key).unwrap();

            (leaf.der().as_ref().to_vec(), root.der().as_ref().to_vec())
        }
    }
}
